proto: ./proto/image_uploader.proto
	protoc -I./proto --go_out=plugins=grpc:api proto/*
#	bundle exec grpc_tools_ruby_protoc -I./proto --ruby_out=client/app/gen/pb/image/upload --grpc_out=client/app/gen/pb/image/upload ./proto/image_uploader.proto

